
name: "HelloDart"

environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  args: ^2.3.0
  build: ^2.3.0
  shelf: ^1.3.0
  shelf_router: ^1.1.2
  shelf_static: ^1.1.0
dev_dependencies: {build_runner: ^2.1.11, build_web_compilers: ^3.2.3}
